version: '3.10'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      # Add any environment variables your app needs here
    volumes:
      # SQLite database in data directory at project root level (same level as src)
      - sqlite-data:/usr/src/app/data
    labels:
      - "traefik.enable=true"
      
      # Domain-based routing
      - "traefik.http.routers.api-domain.rule=Host(`api.polisync.de`)"
      - "traefik.http.routers.api-domain.entrypoints=websecure"
      - "traefik.http.routers.api-domain.tls.certresolver=letsencrypt"
      
      # IP-based routing (no TLS) over port 80
      - "traefik.http.routers.api-ip.rule=HostRegexp(`{ip:[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}}`)"
      - "traefik.http.routers.api-ip.entrypoints=web"
      - "traefik.http.routers.api-ip.priority=1"
      
      # Default service
      - "traefik.http.services.api.loadbalancer.server.port=3000"
    restart: unless-stopped
    networks:
      - traefik-network

  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt
    command:
      # API and dashboard configuration
      - "--api.insecure=false"
      # Docker provider configuration
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-network"
      # Entry points configuration
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # HTTP to HTTPS redirect (only for domain, not IP)
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.priority=10"
      # Let's Encrypt configuration
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=hello@polisync.de"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      # Log configuration
      - "--log.level=INFO"
    networks:
      - traefik-network
    restart: unless-stopped

networks:
  traefik-network:
    driver: bridge

volumes:
  sqlite-data:
    driver: local
  traefik-certificates:
    driver: local